# ==============================================================
# mTLS Policy - STRICT mode cho toàn namespace yas-app
# ==============================================================
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: yas-app-mtls-strict
  namespace: yas-app
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: elasticsearch-disable-mtls
  namespace: yas-app
spec:
  host: "elasticsearch.elasticsearch.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
