apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/DuyHieu251005/yas.git
    targetRevision: HEAD
    path: k8s/charts
    helm:
      releaseName: yas-staging
      valueFiles:
        - values.yaml
      parameters:
        - name: backend.image.tag
          value: latest
        - name: ui.image.tag
          value: latest
        - name: backend.image.pullPolicy
          value: Always
        - name: ui.image.pullPolicy
          value: Always
        - name: backend.service.type
          value: NodePort
        - name: ui.service.type
          value: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: false   # staging: manual approval required
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
