apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: yas-dev-services
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - service: yas-configuration
            image: yas-configuration
          - service: swagger-ui
            image: swagger-ui
          - service: cart
            image: yas-cart
          - service: customer
            image: yas-customer
          - service: inventory
            image: yas-inventory
          - service: media
            image: yas-media
          - service: order
            image: yas-order
          - service: product
            image: yas-product
          - service: search
            image: yas-search
          - service: tax
            image: yas-tax
          - service: storefront-bff
            image: yas-storefront-bff
          - service: backoffice-bff
            image: yas-backoffice-bff
          - service: storefront-ui
            image: yas-storefront
          - service: backoffice-ui
            image: yas-backoffice
  template:
    metadata:
      name: "yas-dev-{{service}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/DuyHieu251005/yas.git
        targetRevision: main
        path: "k8s/charts/{{service}}"
        helm:
          parameters:
            - name: backend.image.tag
              value: 1f6c99b
            - name: ui.image.tag
              value: 1f6c99b
            - name: backend.image.pullPolicy
              value: Always
            - name: ui.image.pullPolicy
              value: Always
            - name: backend.service.type
              value: NodePort
            - name: ui.service.type
              value: NodePort
            - name: backend.image.repository
              value: "duyhieu2005/{{image}}"
            - name: ui.image.repository
              value: "duyhieu2005/{{image}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: yas-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
